// Generated by nuxt-unhead

declare module '#app/nuxt' {
  import { HeadEntry, HeadTag } from '@vueuse/head'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}

type PublicFiles = '/images/favicon.png' | '/images/list.svg' | '/images/logo.png' | '/images/paypal.svg' | '/images/social.png' | '/images/ss1.png' | '/images/ss2.png' | '/images/ss3.png' | '/images/ss4.png' | '/images/ss5.png' | '/images/steam_login.png' | (string & Record<never, never>)
type AssetFiles = (string & Record<never, never>)

declare module '@nuxt/schema' {
  interface HeadAugmentations {
    link: {
      href: PublicFiles | AssetFiles
    }
    script: {
      src: PublicFiles | AssetFiles
    }
  }
}

// ensures we augment
export {}